### ISSUE TITLE
08/06/2024 - TODO

### ISSUE THREAD

**Issue by darsan-in** [cresteem/Richie-JS-DocSite#1]
- [x] Organisation
    - [x] Heading & What is it?
    - [x] Ref link
    - [x] Necessary data / Inputs
    - [x] Function & Parametrs
    - [x] Example of a Instance
    - [x] Output of a Instance 

- [x] Local business
    - [x] Heading & What is it?
    - [x] Ref link
    - [x] Necessary data / Inputs
    - [x] Function & Parametrs
    - [x] Example of a Instance
    - [x] Output of a Instance 

- [x] Software app
    - [x] Heading & What is it?
    - [x] Ref link
    - [x] Necessary data / Inputs
    - [x] Function & Parametrs
    - [x] Example of a Instance
    - [x] Output of a Instance
